// <auto-generated />
using Final_Group_Project.DataBase;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Final_Group_Project.Migrations
{
    [DbContext(typeof(DataBaseContest))]
    [Migration("20230715161437_new")]
    partial class @new
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.9");

            modelBuilder.Entity("Final_Group_Project.Models.Module", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("TEXT");

                    b.Property<int>("Credit")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Code");

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("Final_Group_Project.Models.Student", b =>
                {
                    b.Property<string>("Reg_No")
                        .HasColumnType("TEXT");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("First_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Gpa")
                        .HasColumnType("REAL");

                    b.Property<string>("Last_Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Tel_No")
                        .HasColumnType("INTEGER");

                    b.HasKey("Reg_No");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Final_Group_Project.Models.StudentModule", b =>
                {
                    b.Property<string>("Student_Reg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Module_Code")
                        .HasColumnType("TEXT");

                    b.Property<string>("Grade")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<double>("Marks")
                        .HasColumnType("REAL");

                    b.HasKey("Student_Reg", "Module_Code");

                    b.HasIndex("Module_Code");

                    b.ToTable("studentModules");
                });

            modelBuilder.Entity("Final_Group_Project.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Final_Group_Project.Models.StudentModule", b =>
                {
                    b.HasOne("Final_Group_Project.Models.Module", "Module")
                        .WithMany("StudentModules")
                        .HasForeignKey("Module_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Final_Group_Project.Models.Student", "Student")
                        .WithMany("StudentModules")
                        .HasForeignKey("Student_Reg")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("Final_Group_Project.Models.Module", b =>
                {
                    b.Navigation("StudentModules");
                });

            modelBuilder.Entity("Final_Group_Project.Models.Student", b =>
                {
                    b.Navigation("StudentModules");
                });
#pragma warning restore 612, 618
        }
    }
}
